### ISSUE TITLE
v20210517: strange numbers for wind data

### ISSUE THREAD

**Issue by W-Geronius** [kdschmidt1/avnav-more-nmea-plugin#1]
Hi,

Unfortunately I can't figure out some of the wind values as output by the plugin. In my setup all data (apparent wind, course and mag heading) originate from signalK:  in the attached screenshot (output of `wget http://10.10.10.1:8080/viewer/avnav_navi.php?request=gps` ) you find these marked by checkmarks in blue circles. 

Some derived values (greenish check) are correct, however I have no explanation for the others marked by question mark.
Would you mind to have a look into this?

<img width="684" alt="CAPT-20210530-183736" src="https://user-images.githubusercontent.com/18160302/120114269-ac8e9e80-c17e-11eb-967d-32ab02334a3f.png">

**Comment by kdschmidt1** [comment]
the bug was caused by using some values from a previous run (see [commit](https://github.com/kdschmidt1/avnav-more-nmea-plugin/commit/eae506ba7096016b9662ea978911bd5ff68c36e6)).
Nevertheless the wind-direction calculation (AWD and TWD) was correct, based on wind-angle and COG. 
Closed with [v20210531](https://github.com/kdschmidt1/avnav-more-nmea-plugin/releases/tag/20210531)

**Comment by W-Geronius** [comment]
Sorry and excuse me, I can't follow ... what's the impact of COG? To my understanding COG is irrelevant, especially as speed is zero - it reflects erratic GPS jumps (the 'boat' is presently moored on my desk). When moored AWA should equal to TWA, as well as AWS to TWS.  Which they in fact are in the latest version ... thanks
AWA relates to the boat's bow (the bow hardly ever points in exact COG direction, thinking of leeway (drift) or current) - so HDT should be used to determine AWD (and TWD, of course). 
Just my 2 cents - maybe we can discuss via chat or forum?

**Comment by W-Geronius** [comment]
just an addition: are you aware of the mariner's odd habit (including signalK) to define 'true wind' as windspeed over water  - not as windspeed over ground (GWD) as the rest of the world in meteorology and aviation does) 
Unless you are boating on a river the difference might be marginal - however STW would have to be used instead of SOG
