### ISSUE TITLE
revision/cleanup

### ISSUE THREAD

**Issue by quantenschaum** [kdschmidt1/avnav-more-nmea-plugin#10]
Ich hab mir mal dieses Plugin angesehen und nach meinem Geschmack überarbeitet. Schau dir das doch bitte mal an und dann können wir sehen, was wir daraus machen.

https://github.com/quantenschaum/calculated-data-plugin

**Comment by kdschmidt1** [comment]
Hey Adam,Nein, lass mal. Ich wollte es sowieso gerade als veraltet und nicht mehr unterstützt deklarieren und aus dem repository herausnehmen lassen. Bis auf die desclination kann es direkt mit sailsteer ersetzt werden. Falls Bedarf an der deklination besteht, kann ich sie da noch einbauen.ich möchte nicht zwei plugins mit demselben content pflegen müssen. Trotzdem danke und Gruß KdVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Adam ***@***.***> Datum: 27.02.24  13:07  (GMT+01:00) An: kdschmidt1/avnav-more-nmea-plugin ***@***.***> Cc: Subscribed ***@***.***> Betreff: [kdschmidt1/avnav-more-nmea-plugin] revision/cleanup (Issue #10) 
Ich hab mir mal dieses Plugin angesehen und nach meinem Geschmack überarbeitet. Schau dir das doch bitte mal an und dann können wir sehen, was wir daraus machen.
https://github.com/quantenschaum/calculated-data-plugin

**Comment by quantenschaum** [comment]
Das stimmt, die Berechnung ist redundant, da hab ich auch schon drüber nachgedacht. Was es jedoch macht ist, die berechneten Werte wieder als NMEA ins System einspeisen. Das könnte man ja ins SailInstrument auch noch einbauen, geht dann aber thematisch etwas darüber hinaus, was es eigentlich machen soll.

**Comment by quantenschaum** [comment]
merged into https://github.com/kdschmidt1/Sail_Instrument
