### ISSUE TITLE
v20210517: german description

### ISSUE THREAD

**Issue by W-Geronius** [kdschmidt1/avnav-more-nmea-plugin#2]
A german text is displayed when clicking 'help' in AvNav settings - should be in english
 'description': 'Filter  für auszugebende NMEA records',

Does this filter specify records to be sent or records to be omitted?

**Comment by kdschmidt1** [comment]
Translation corrected.
The filter specifies which of the transmitted records should be omitted (filtered)!
Closed with [v20210531](https://github.com/kdschmidt1/avnav-more-nmea-plugin/releases/tag/20210531)

**Comment by W-Geronius** [comment]
installed new version via dpkg, but german text still present. Maybe something went wrong with packaging? Or will it become effective only when officially released via Andreas update?
Thanks for the quick response anyway !!

<img width="780" alt="CAPT-20210531-155757" src="https://user-images.githubusercontent.com/18160302/120204869-94c02480-c229-11eb-888b-a41be425f10e.png">
<img width="780" alt="CAPT-20210531-155831" src="https://user-images.githubusercontent.com/18160302/120204867-94278e00-c229-11eb-8356-ed400220e1aa.png">

**Comment by wellenvogel** [comment]
Did  ou restart AvNav after installing?

**Comment by W-Geronius** [comment]
good hint - I restarted, by clicking the restart button in AvNav Server Status. It told me 'restart triggered', but in fact it didn't.
Just after reading your comment, I restarted via command line and saw the restart asking for a `systemctl daemon-reload`.  
So, that's a Server Status page issue then ...
Now the english text is there!
