### ISSUE TITLE
plugin is polluting the avnav log

### ISSUE THREAD

**Issue by wellenvogel** [kdschmidt1/avnav-more-nmea-plugin#5]
The plugin is writing an error to the server log every ~500ms:
`2021-06-07 21:00:17,705-4381-4445-Plugin: system-more-nmea-ERROR- error calculating TrueWind-Data {'updatealarm': 1623092250.487675, 'updateleg': 1623092250.487827, 'updateroute': 1623092250.487896, 'signalk': {'propulsion': {'1': {'temperature': 321.2639999999999}}, 'navigation': {'position': {'longitude': 13.545393666666667, 'latitude': 52.67041716666667}, 'courseOverGroundTrue': 0, 'speedOverGround': 0.12861114369260085, 'magneticVariation': 0, 'magneticVariationAgeOfService': 1623092417, 'datetime': '2021-06-07T19:00:17.000Z', 'courseOverGroundMagnetic': 0, 'gnss': {'methodQuality': 'GNSS Fix', 'satellites': 5, 'antennaAltitude': 72, 'horizontalDilution': 2, 'differentialAge': 0, 'differentialReference': 0}}, 'environment': {'wind': {'speedApparent': 0, 'angleApparent': -0.08203047486246347}}, 'design': {'aisShipType': {'name': 'Sailing', 'id': 36}}, 'notifications': {'server': {'newVersion': {'state': 'alert', 'method': [], 'message': 'A new version (1.39.0) of the server is available'}}}, 'name': 'Quetzal'}, 'satInview': 12, 'track': 0.0, 'speed': 0.12861111111111112, 'AWA': -4.699999999999989, 'AWS': (0.0, 514444), 'test': 1550, 'windAngle': -4.7, 'windReference': 'R', 'windSpeed': 0.0, 'mode': 2, 'lat': 52.67041716666667, 'lon': 13.545393666666667, 'time': '2021-06-07T19:00:17Z', 'satUsed': 5, 'MagVar': 4.520998386818003, 'AWD': 355.3}
`
From the log it is impossible to tell what the error really is.
Beside the error itself the plugin should never write an error with that frequency.
So the best approach is to write out the error once and only if the condition changes just write a new error.
With that many errors in the log it is impossible to find problems.
Plugin version: 20210603

**Comment by kdschmidt1** [comment]
Im just on the way to the baltic sea. So it will take some time to check.

**Comment by kdschmidt1** [comment]
Hallo Andreas,
Im quite sure, that the error is caused by a malformatted nmea input sentence ($VWR or $MWV) with a missing comma. This would explain why the AWS in the error message is a list and not a single float. Can you please check or send me an example of your input data?

**Comment by wellenvogel** [comment]
Sorry for the delay but currently I'm not that often at my desk.
Will collect some input data that triggers the problem.

**Comment by wellenvogel** [comment]
Just collected some NMEA log for the problem.
[nmea-wind.log](https://github.com/kdschmidt1/avnav-more-nmea-plugin/files/6680707/nmea-wind.log)
BTW: AvNav has no problem in decoding the wind data.
