### ISSUE TITLE
v20210626: HDGt and HDGm become negative when headingMag is greater than 180°

### ISSUE THREAD

**Issue by W-Geronius** [kdschmidt1/avnav-more-nmea-plugin#6]
Heading values should be in range 0-359°, not -179 to +179
<img width="460" alt="CAPT-20220227-160932" src="https://user-images.githubusercontent.com/18160302/155888243-7ec144ef-5edf-4b07-a45d-5b8a3638a103.png">

**Comment by kdschmidt1** [comment]
Fix suggestion #7 merged to close
